site:
    base : templates
    config :
        title : What's my User-Agent?
        description : Do you want to know what is your User-Agent? Yes, here it is.
        author: mysqto
        qr: templates/qr.svg
        geoip: templates/GeoLite2-City.mmdb
        gaid: UA-119735834-1
        keywords:
            - UserAgent
            - User-Agent
            - UA
            - MyUserAgent
            - ua
            - my
            - IP
            - IP Address
        domain:
            - myua.is
            - www.myua.is
    https:
        enabled: true
        only: true
        port: 443
        cert: cert
    http:
        port: 80
